name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write  # for trusted publishing (recommended)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build wheel and sdist
        run: |
          uv build

      - name: Publish to PyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          # If not using trusted publishing, set `password` to PYPI API token
          # password: ${{ secrets.PYPI_API_TOKEN }}

